#!/usr/bin/env bash
# set up
if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install nginx
    sudo ufw allow "Nginx HTTP"
fi
folder=("/data" "/data/web_static/" "/data/web_static/releases/" "/data/web_static/shared/" "/data/web_static/releases/test/")

for fol in ${folder[@]}; do
    if [ ! -d $fol ]; then
        mkdir -p $fol
    fi
done

link="/data/web_static/current"
target="/data/web_static/releases/test/"

if [ -L $link ]; then
    rm -f $link
fi

ln -s  $target $link
chown $ubuntu:$ubuntu /data/

echo "<html>
  <head>
  </head>
  <body>
    Holberton School
  </body>
</html>" > /data/web_static/releases/test/index.html
echo "
server {
	listen 80 default_server;

	add_header X-Served-By 419885-web-02;

	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {


	error_page 404 /custom_404.html;

		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
  location /hbnb_static{
    alias /data/web_static/current/;
  }

}

">/etc/nginx/sites-available/default
service nginx restart
